from decimal import Decimal

DEFAULT_TARGET_KCAL_FLOOR = Decimal("1200")
MAX_KCAL = Decimal("20000")
MAX_MACRO_GRAMS = Decimal("2000")
MAX_TARGET_SCHEDULE_ITEMS = 1000
TARGET_DECIMAL_PLACES = 2
TARGET_QUANTUM = Decimal("0.01")
