from opennosh_api.exercises.schemas import (
    ExerciseAttribution,
    ExerciseDetail,
    ExerciseExport,
    ExerciseTranslation,
    ExerciseTranslationAttribution,
)
from opennosh_api.exports.schemas import (
    AccountExport,
    BodyMetricExport,
    CommunityFoodExport,
    CommunityFoodExportEntry,
    CustomFoodExport,
    LogEntryExport,
    PrivateDataExport,
    RecipeExport,
    RecipeIngredientExport,
    TargetExport,
    WorkoutExport,
    WorkoutSetExport,
)
from opennosh_api.foods.schemas import OpenFoodFactsExport, OpenFoodFactsExportEntry


def test_version_one_export_schema_snapshot() -> None:
    expected_fields = {
        PrivateDataExport: (
            "schema_version",
            "dataset",
            "access",
            "notice",
            "account",
            "custom_foods",
            "recipes",
            "recipe_ingredients",
            "log_entries",
            "targets",
            "body_metrics",
            "workouts",
            "workout_sets",
        ),
        AccountExport: ("id", "email", "created_at", "settings"),
        CustomFoodExport: ("id", "created_at", "name", "nutrients", "portions"),
        RecipeExport: ("id", "name", "yield_grams", "is_public"),
        RecipeIngredientExport: (
            "id",
            "recipe_id",
            "position",
            "food_source_table",
            "food_source_id",
            "food_source_key",
            "food_name",
            "grams",
            "computed_nutrients",
        ),
        LogEntryExport: (
            "id",
            "logged_at",
            "meal_slot",
            "food_source_table",
            "food_source_id",
            "food_source_key",
            "food_name",
            "quantity_amount",
            "quantity_unit",
            "portion_name",
            "grams",
            "computed_nutrients",
        ),
        TargetExport: (
            "id",
            "day_type",
            "kcal",
            "protein_g",
            "carb_g",
            "fat_g",
            "active_from",
            "active_until",
            "below_floor_confirmed",
            "safety_review_required",
            "safety_floor_kcal",
        ),
        BodyMetricExport: ("id", "recorded_at", "metric_type", "value", "unit"),
        WorkoutExport: ("id", "performed_at", "notes"),
        WorkoutSetExport: (
            "id",
            "workout_id",
            "exercise_id",
            "position",
            "reps",
            "load_value",
            "load_unit",
        ),
        CommunityFoodExport: (
            "schema_version",
            "dataset",
            "license",
            "license_url",
            "notice",
            "entries",
        ),
        CommunityFoodExportEntry: (
            "source",
            "pack_id",
            "pack_version",
            "pack_license",
            "slug",
            "name",
            "name_local",
            "locale",
            "category",
            "contributed_by",
            "provenance",
            "source_uri",
            "source_license",
            "source_note",
            "basis",
            "nutrients",
            "portions",
            "density_g_per_ml",
        ),
        OpenFoodFactsExportEntry: (
            "source",
            "barcode",
            "product_name",
            "brand",
            "nutrients",
            "source_url",
            "database_license",
            "contents_license",
            "attribution_text",
        ),
        OpenFoodFactsExport: (
            "schema_version",
            "dataset",
            "source",
            "source_url",
            "database_license",
            "database_license_url",
            "contents_license",
            "contents_license_url",
            "notice",
            "entries",
        ),
        ExerciseExport: (
            "schema_version",
            "dataset",
            "source",
            "source_url",
            "license_spdx",
            "license_url",
            "share_alike_notice",
            "entries",
        ),
        ExerciseDetail: (
            "id",
            "slug",
            "name",
            "muscle_groups",
            "equipment",
            "translations",
            "attribution",
            "source_updated_at",
        ),
        ExerciseAttribution: (
            "source",
            "source_id",
            "source_url",
            "derivative_source_url",
            "license_spdx",
            "license_url",
            "author",
            "author_url",
            "attribution_text",
            "translations",
        ),
        ExerciseTranslation: (
            "source_id",
            "source_uuid",
            "language_id",
            "name",
            "description",
            "aliases",
            "notes",
            "source_url",
            "derivative_source_url",
            "license_spdx",
            "license_url",
            "license_title",
            "author",
            "author_url",
            "attribution_text",
        ),
        ExerciseTranslationAttribution: (
            "source_id",
            "language_id",
            "source_url",
            "derivative_source_url",
            "license_spdx",
            "license_url",
            "license_title",
            "author",
            "author_url",
            "attribution_text",
        ),
    }

    for model, fields in expected_fields.items():
        assert tuple(model.model_fields) == fields
