from __future__ import annotations

DEVELOPMENT_PUBLIC_KEY = "Laz0b4AQMs1TfE090-MRSPubDqxptaEJ-HZXEsZe_lw"
ACCEPTANCE_MANIFEST_KEY_ID = "acceptance-manifest-v1"
ACCEPTANCE_MANIFEST_VERIFYING_KEY = "DA0jKzf9uc8nFvAVYisKb4L8PmPIHwA_eZLnTRtNH1c"
ACCEPTANCE_RECEIPT_KEY_ID = "acceptance-receipt-v1"
ACCEPTANCE_RECEIPT_VERIFYING_KEY = "ALKuPFTKPQrs_XfTNdyRlw0W0IHVg_P9dNzVFEw-lq8"

NON_PRODUCTION_KEY_IDS = frozenset(
    {"development", ACCEPTANCE_MANIFEST_KEY_ID, ACCEPTANCE_RECEIPT_KEY_ID}
)
NON_PRODUCTION_PUBLIC_KEYS = frozenset(
    {
        DEVELOPMENT_PUBLIC_KEY,
        ACCEPTANCE_MANIFEST_VERIFYING_KEY,
        ACCEPTANCE_RECEIPT_VERIFYING_KEY,
    }
)
